In [2]:
import numpy as np
dataset_filename="affinity_dataset.txt"
X=np.loadtxt(dataset_filename)

In [3]:
print (X[:5])

[[ 0.  0.  1.  1.  1.]
 [ 1.  1.  0.  1.  0.]
 [ 1.  0.  1.  1.  0.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  1.  0.  0.  1.]]


In [3]:
print(X[:5])

[[ 0.  0.  1.  1.  1.]
 [ 1.  1.  0.  1.  0.]
 [ 1.  0.  1.  1.  0.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  1.  0.  0.  1.]]


In [4]:
#计算“如果买了苹果，也会购买香蕉”的支持度与置信度。首先计算购买苹果的数量
num_apple_purchases=0
for sample in X:
    if sample[3]==1:  #购买了苹果
        num_apple_purchases+=1
print("{0} 个人购买了苹果" .format(num_apple_purchases))

36 个人购买了苹果


In [5]:
#计算“如果买了苹果，也会购买香蕉”的支持度与置信度。第二部计算购买香蕉的数量
num_pear_purchases=0
for sample in X:
    if sample[4]==1: #购买了香蕉
        num_pear_purchases+=1
print("{0} 个人购买了香蕉".format(num_pear_purchases))

59 个人购买了香蕉


In [14]:
#从（苹果，香蕉）的个例练习如何计算支持度与置信度，即sample[3]=1 and sample[4]=1.首先定义特征组
features=['面包','牛奶','奶酪','苹果','香蕉']

In [8]:
#定义并计算规则应验、规则无效
rule_valid=0 #规则应验的次数
rule_invalid=0 #规则无效的次数
num_occurances=0 #条件发生的总次数
for sample in X:
    if sample[3]==1:
        num_occurances+=1
        if sample[4]==1:
            rule_valid+=1
        else: rule_invalid+=1
print("规则应验次数为{0}".format(rule_valid))
print("规则无效次数为{0}".format(rule_invalid))
print("条件发生总次数为{0}".format(num_occurances))

规则应验次数为21
规则无效次数为15
条件发生总次数为36


In [9]:
#计算支持度、置信度
support=rule_valid
confidence=rule_valid/num_occurances
print("购买苹果的人也购买了香蕉的支持度为{0}".format(support))
print("购买苹果的人也购买了香蕉的置信度为{0:.1f}%".format(100*confidence))

购买苹果的人也购买了香蕉的支持度为21
购买苹果的人也购买了香蕉的置信度为58.3%


In [20]:
#5类产品可随意计算任意条件和结论规则，即参数化条件premise和结论conclusion，首先建立条件和结论的字典信息
from collections import defaultdict
valid_rule=defaultdict(int)
invalid_rule=defaultdict(int)
num_premise_occurances=defaultdict(int)
for sample in X: #对数据集中的每条记录
    for premise in range(len(features)): #对五种可能的条件
        if sample[premise]==0:
            continue #不满足规则的条件部分，则跳过
        num_premise_occurances[premise]+=1
        for conclusion in range(len(features)):
            if premise==conclusion:continue#条件与结论相同，即如果买了苹果，则买了苹果。此种情况则跳过
            if sample[conclusion]==1:
                valid_rule[(premise,conclusion)]+=1
            else:
                invalid_rule[(premise,conclusion)]+=1
support=valid_rule
confidence=defaultdict(float)
for premise,conclusion in valid_rule.keys():
    confidence[(premise,conclusion)]=valid_rule[(premise,conclusion)]/num_premise_occurances[premise]          
            

In [21]:
def print_rule(premise,conclusion,support,confidence,features):
    premise_name=features[premise]
    conclusion_name=features[conclusion]
    print("如果客户购买{0}，则也会购买{1}".format(premise_name,conclusion_name))
    print("支持度为{0}".format(support[(premise,conclusion)]))
    print("置信度为{0:.3f}".format(confidence[(premise,conclusion)]))

In [22]:
premise=3
conclusion=4
print_rule(premise,conclusion,support,confidence,features)

如果客户购买苹果，则也会购买香蕉
支持度为21
置信度为0.583
